import Head from "next/head";
import Contact from "../components/Contact";
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";
import ProjectContainer from "../components/Projects";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nnamdi | FrontEnd Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
      <Skills />
      <ProjectContainer />
      <Contact />
    </div>
  );
}
